### ISSUE TITLE
build error: webpack missing

### ISSUE THREAD

**Issue by Danfro** [milikhin/seabass2#12]
When building on ubuntu 20.04 it breaks with an error that webpack is missing:

```
npm run build

> seabass-editor@0.3.1 build /media/Daten/Forks/seabass2
> webpack

sh: 1: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! seabass-editor@0.3.1 build: `webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the seabass-editor@0.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-05-22T18_52_34_405Z-debug.log

```
[2020-05-22T18_52_34_405Z-debug.log](https://github.com/milikhin/seabass2/files/4669894/2020-05-22T18_52_34_405Z-debug.log)

After installing webpack, it throws an error `copy-webpack-plugin`is missing.
```
pm run build

> seabass-editor@0.3.1 build /media/Daten/Forks/seabass2
> webpack

/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module 'copy-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/media/Daten/Forks/seabass2/webpack.config.js:2:20)
    at Module._compile (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/usr/share/nodejs/yargs/yargs.js:620:18)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/nodejs/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! seabass-editor@0.3.1 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the seabass-editor@0.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-05-22T18_59_09_144Z-debug.log

```

[2020-05-22T18_59_09_144Z-debug.log](https://github.com/milikhin/seabass2/files/4669901/2020-05-22T18_59_09_144Z-debug.log)

So I am not able to properly build the app (trying for UT).
Well, clickable builds the app, but it does not work (= show files).

**Comment by milikhin** [comment]
Just to be sure: you've run `npm install` command (before executing `npm run build`) in the `seabass2` directory?

Build steps:
1. `npm install` (in the **seabass2** directory). At this step a new directory called **seabass2/node_modules** will be created. All the build dependencies are installed there.
2. `npm run build`
3. `clickable`

**Comment by milikhin** [comment]
Both `webpack` and `copy-webpack-plugin` packages should be installed for you automatically at the first step

**Comment by Danfro** [comment]
I did `npm install` but there seems to be no `node_submodules`. So maybe something went wrong at that step already.

**Comment by milikhin** [comment]
Seems like something went wrong with `npm install`. I would suggest to try again and check if it creates `node_modules` directory.

**Comment by Danfro** [comment]
Tried it again. Now the `node_submodules` is there. I guess that was because webpack was not installed before?

Also `npm install` brings up some warnings. But i guess that does not harm.
```
pm install

> core-js@2.6.11 postinstall /media/Daten/Forks/seabass2/node_modules/babel-polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /media/Daten/Forks/seabass2/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall /media/Daten/Forks/seabass2/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm WARN seabass-editor@0.3.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1172 packages from 499 contributors and audited 1174 packages in 36.307s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by Danfro** [comment]
OK. Now build works too. And clickable provides a working app. :+1:

**Comment by milikhin** [comment]
Looks fine now! The warnings are OK.
Shouldn't be related to webpack, as it is just an NPM package itself.

It just happens to the first package that is required by `npm run build` script, so Node throws a error about webpack.

**Comment by milikhin** [comment]
> OK. Now build works too. And clickable provides a working app.

Great! I'm closing the issue then!

**Comment by Danfro** [comment]
Yes. Thanks. Maybe you can find somehing in the logs that might help to improve the script to avoid my issue for other.
